<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>White Rabbit</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="Assets/Js/actions.js"></script>
    <link href="Assets/CSS/style.css" rel="stylesheet">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">

</head>

<body>

<header id=”mainheader” class=“branding” role=“banner”>
    <img id="logo" src="Assets/Img/rabbit.jpg">
    <H1>Follow The White Rabbit</H1>


    <?php if (array_key_exists("error",$_SESSION)):?>
        <?= $_SESSION["error"]?>
    <?php endif ?>


    <?php if(array_key_exists("id",$_SESSION)):?>


        <p>Welcome back <?=$_SESSION["name"] ?></p>
        <p><a href="logout.php">logout</a></p>

    <?php else: ?>
        <form method="post" action="login.php">
            <input type="text" name="login">
            <input type="password" name="password">
            <input type="submit" value="Down the rabbit hole">
        </form>

        <a href="#" id="inscription" > Pas encore inscrit ?</a>

        <form id="wrap" class="wrap hide" action="inscription.php" method="post">

            <input type="text" placeholder="Votre nom" name="createLogin">
            <input type="text" placeholder="Votre mail" name="createMail">
            <input type="text" placeholder="Votre mode passe" name="createPassword">

            <input type="submit" value="S'inscrire">
        </form>




    <?php endif ?>



</header>


<nav id=”main” role=“navigation”>
    <ul>
        <li>
            <a>            </a>
        </li>
    </ul>



</nav>