<section id=”section-main-accueil” role=“main”>
    <?php var_dump($posts); ?>


    <?php if (array_key_exists("admin",$_SESSION)&&$_SESSION["admin"]==1): ?>
        <a href='addArticle.php' style="font-size: 100px;"><i class="fa fa-plus-square"></i></a>
    <?php endif ?>
    <?php foreach($posts as $post): ?>

        <?php var_dump($post); ?>

        <article class="norm">
        <h2><?=$post["title"]?></h2>
        <img src="Assets/Img/Avatar/<?=$post["avatar_src"]?>">
        <a><?=$post["name"]?></a>
        <a><?=$post["creation_date"]?></a>


        <figure>
            <div id="cont">
                <?php $pieces = explode(",", $post['image_src']);?>

            <?php foreach($pieces as $value) :?>
            <?php if(empty($value)==false): ?>
            <img class="disp" src="Assets/Img/Art/<?=$value?>">
            <?php endif ?>
            <?php endforeach ?>
            <?php if (array_key_exists("admin",$_SESSION)&&$_SESSION["admin"]==1): ?>

                <div id='control'>
                    <div id="controlers">
                        <a href=''><i class="fa fa-pencil-square"></i></a>
                        <a href='delete.php?delete=<?=$post['id'] ?>'><i class="fa fa-trash-o"></i></a>
                    </div>
                </div>

            <?php endif ?>
            </div>
            <figcaption><?=$post["caption"]?></figcaption>
        </figure>

            <div class="block">
            <p><?=$post["content"]?></p>
        </div>


        <aside>
        <div>
            <img src=""><span>User</span><img src=""><span>Date</span>
            <div>CommentsCommentsCommentsCommentsComments</div><img id =src="">
        </div>
        <div>
            <form method="post" action="add_comment.php">
                <fieldset>
                <input type="text" name="comment">
                <input type="submit" value="Send">
                </fieldset>
            </form>
        </div>
        </aside>
        </article>

    <?php  endforeach ?>


</section>
