<section id=”section-main-accueil” role=“main”>

    <?php foreach($posts as $post): ?>
    <?='
    <article class="norm">
    <h2>'.$post["title"].'</h2>
    <strong>'.$post["creation_date"].'</strong>
    <figure>
        <img src="'.$post["image_src"].'">
        <figcaption>'.$post["caption"].'</figcaption>
    </figure>
    <div class="block">
        <p>'.$post["content"].'</p>
    </div>
    </article>

    <aside>

    <div>
        <img src=""><span>Date</span>
        <div>Comments</div>
    </div>
    <div>
        <form method="post" action="add_comment.php">
            <input type="text" name="comment">
            <input type="submit" value="Send">
        </form>
    </div>
    </aside>
      ' ?>
    <?php  endforeach ?>


</section>
