<section id=”section-main-accueil” role=“main”>

    <article class="norm">
        <h2> titre</h2>
        <figure>
            <img src="">
            <figcaption>caption</figcaption>
        </figure>
        <div class="block">
            <p>Mon text ici</p>
        </div>
    </article>
    <aside>
        <div>
            <span>123</span><span>date</span>
            <div>CommentsCommentsCommentsCommentsCommentsCommentsComments</div>
            <div><img src=""></div>
        </div>
        <div>
            <img src=""><span>Date</span>
            <div>Comments</div>
        </div>
        <div>
            <form method="post" action="add_comment.php">
                <input type="text" name="comment">
                <input type="submit" value="Send">
            </form>
        </div>
    </aside>



</section>
